apiVersion: v1
kind: ConfigMap
metadata:
  name: dispatcher-config
  labels:
    app: dispatcher-service
data:
  application.yml: |
    spring:
      rabbitmq:
        #host: polar-rabbitmq
        host: 192.168.56.30
        port: 30567